### ISSUE TITLE
How does this model work when do inference?

### ISSUE THREAD

**Issue by FT-ZHOU-ZZZ** [mdswyz/DiCMoR#6]
Thanks for your interesting work.
In your released code, I found both of training and test phases require label as model's inputs.
When do inference, the label of test sample MUST be unknown. I wonder how your model works in such case. 
Although the label input in forward function has been set to None by default, you didn't provide any solution when label is None (do inference).

**Comment by mdswyz** [comment]
Thanks for your attention. For inference only, the labels are not required because the labels are merely used to calculate the loss. You can extract the do_test() function in [DICMOR.py](https://github.com/mdswyz/DiCMoR/blob/main/trains/singleTask/DICMOR.py), simply write a script for model and dataset loading, removing labels and loss calculations (It's fine not to remove it, because there is no backpropagation in the inference phase).

**Comment by FT-ZHOU-ZZZ** [comment]
Thanks for your prompt reply.
`def forward(self, text, audio, video, label=None, num_modal=None):
....
for i in range(label.size(0)):
....
`
If set label to None, it seems your code will raise "AttributeError: 'NoneType' object has no attribute 'size'"

**Comment by mdswyz** [comment]
A simple way is to define a label tensor, where the value could be padded arbitrarily (e.g., zero)
